window.APP_CONFIG = {
  version_name: "v1-public-static",
  is_active: true,
  allometric_exponent: 0.67,
  readability_scale: 10,
  rounding_precision: 1,
  multipliers: {
    pullup: 1.6,
    dip: 1.2,
    muscleup: 2.0,
    bench: 1.7,
    squat: 1.1,
    deadlift: 0.9,
    ohp: 2.2,
    biceps: 2.8,
  },
  warnings: {
    bodyweight_min: 30,
    bodyweight_max: 250,
    bench_max: 500,
    squat_max: 600,
    deadlift_max: 600,
    ohp_max: 250,
    biceps_max: 200,
    pullup_added_max: 200,
    dip_added_max: 250,
    muscleup_added_max: 150,
  },
  labels: {
    pullup: "Pull-up +kg",
    dip: "Dip +kg",
    muscleup: "Muscle-up +kg",
    bench: "Bench",
    squat: "Squat",
    deadlift: "Deadlift",
    ohp: "OHP",
    biceps: "Biceps",
  },
};
